
const ROLES = {
    ADMIN: 'admin',
    TEACHER: 'teacher',
    STUDENT: 'student'
};

const PERMISSIONS = {
    CREATE_USER: [ROLES.ADMIN],
    READ_ALL_USERS: [ROLES.ADMIN],
    READ_USER: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
    UPDATE_USER: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
    DELETE_USER: [ROLES.ADMIN],
    
    CREATE_STUDENT: [ROLES.ADMIN],
    READ_ALL_STUDENTS: [ROLES.ADMIN, ROLES.TEACHER],
    READ_STUDENT: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
    UPDATE_STUDENT: [ROLES.ADMIN, ROLES.TEACHER],
    DELETE_STUDENT: [ROLES.ADMIN],
    
    CREATE_TEACHER: [ROLES.ADMIN],
    READ_ALL_TEACHERS: [ROLES.ADMIN, ROLES.TEACHER],
    READ_TEACHER: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
    UPDATE_TEACHER: [ROLES.ADMIN],
    DELETE_TEACHER: [ROLES.ADMIN],
    
    CREATE_COURSE: [ROLES.ADMIN],
    READ_ALL_COURSES: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
    READ_COURSE: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
    UPDATE_COURSE: [ROLES.ADMIN, ROLES.TEACHER],
    DELETE_COURSE: [ROLES.ADMIN],
    
    CREATE_ENROLLMENT: [ROLES.ADMIN, ROLES.STUDENT],
    READ_ALL_ENROLLMENTS: [ROLES.ADMIN, ROLES.TEACHER],
    READ_ENROLLMENT: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
    UPDATE_ENROLLMENT: [ROLES.ADMIN, ROLES.TEACHER],
    DELETE_ENROLLMENT: [ROLES.ADMIN],
    
    CREATE_GRADE: [ROLES.ADMIN, ROLES.TEACHER],
    READ_ALL_GRADES: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
    READ_GRADE: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
    UPDATE_GRADE: [ROLES.ADMIN, ROLES.TEACHER],
    DELETE_GRADE: [ROLES.ADMIN],
    
    CREATE_SCHEDULE: [ROLES.ADMIN],
    READ_ALL_SCHEDULES: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
    READ_SCHEDULE: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
    UPDATE_SCHEDULE: [ROLES.ADMIN, ROLES.TEACHER],
    DELETE_SCHEDULE: [ROLES.ADMIN],
};

/**
 * @param {Object} user
 * @param {string} permission 
 * @returns {boolean} 
 */
const hasPermission = (user, permission) => {
    if (!user || !user.role) return false;
    
    const allowedRoles = PERMISSIONS[permission];
    if (!allowedRoles) return false;
    
    return allowedRoles.includes(user.role);
};

module.exports = {
    ROLES,
    PERMISSIONS,
    hasPermission
};